"""remove freebies column from company and dev models

Revision ID: 01ce961ade7a
Revises: d80ecd2b5755
Create Date: 2023-02-19 17:39:35.850283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ce961ade7a'
down_revision = 'd80ecd2b5755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
