"""add companies and devs column

Revision ID: 26bf9245edd8
Revises: 3878f09cc0d1
Create Date: 2023-02-19 18:01:57.276098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bf9245edd8'
down_revision = '3878f09cc0d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
