"""add companies and dev columns to Dev and Company models

Revision ID: 360104a16ec3
Revises: adc8a10a6a91
Create Date: 2023-02-19 17:34:35.819131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360104a16ec3'
down_revision = 'adc8a10a6a91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
