"""update columns in all models

Revision ID: 368887942050
Revises: 3c9f55a8e0f0
Create Date: 2023-02-19 18:24:36.349607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368887942050'
down_revision = '3c9f55a8e0f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
