"""add companies and devs column

Revision ID: 3878f09cc0d1
Revises: 72a85d4cdd93
Create Date: 2023-02-19 18:00:31.979485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3878f09cc0d1'
down_revision = '72a85d4cdd93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
