"""add freebies column

Revision ID: 3c9f55a8e0f0
Revises: fde6eff10051
Create Date: 2023-02-19 18:10:17.051436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9f55a8e0f0'
down_revision = 'fde6eff10051'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
