"""add creator argument to association proxies

Revision ID: 3e4e56a36c06
Revises: 49ce7f209000
Create Date: 2023-02-19 19:02:10.165837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4e56a36c06'
down_revision = '49ce7f209000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
