"""fix dev model's association proxy

Revision ID: 49ce7f209000
Revises: a60622710f36
Create Date: 2023-02-19 18:43:43.814055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ce7f209000'
down_revision = 'a60622710f36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
