"""removes devs and companies column from company and dev class

Revision ID: 72a85d4cdd93
Revises: 01ce961ade7a
Create Date: 2023-02-19 17:51:32.214120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a85d4cdd93'
down_revision = '01ce961ade7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
