"""add companies and dev columns to Dev and Company models

Revision ID: 83f2099750d9
Revises: 360104a16ec3
Create Date: 2023-02-19 17:35:38.732954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f2099750d9'
down_revision = '360104a16ec3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
