"""add companies and dev columns to Dev and Company models

Revision ID: adc8a10a6a91
Revises: 37bec55e05b9
Create Date: 2023-02-19 17:33:24.164266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc8a10a6a91'
down_revision = '37bec55e05b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
