"""add columns

Revision ID: be53d5d90e26
Revises: 26bf9245edd8
Create Date: 2023-02-19 18:04:25.493786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be53d5d90e26'
down_revision = '26bf9245edd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
