"""remove freebies column from company and dev models

Revision ID: d80ecd2b5755
Revises: fd919db5f775
Create Date: 2023-02-19 17:39:21.639654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80ecd2b5755'
down_revision = 'fd919db5f775'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
