"""remove company and dev column from Freebie model

Revision ID: fd919db5f775
Revises: 83f2099750d9
Create Date: 2023-02-19 17:37:58.714654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd919db5f775'
down_revision = '83f2099750d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
