"""add columns

Revision ID: fde6eff10051
Revises: be53d5d90e26
Create Date: 2023-02-19 18:05:25.391139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde6eff10051'
down_revision = 'be53d5d90e26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
